resolver: lts-11.4
packages:
- .

ghc-options:
  # Applied only to those under the "packages" stanza below:
  "$locals":
    -threaded
    -rtsopts
    -with-rtsopts=-T
    -Wall
    -Werror
    -Wincomplete-uni-patterns
    -Wredundant-constraints
